# list1=[10,20,30,40]
# list2=[100,200,300,400]
# i=0
# a=[]
# b=[]
# while i<len(list1) and i<len(list2):
#     a.append(list1[i])
#     b.append(list2[-i])
#     i=i+1
# j=0
# while j<len(a) and j<len(b):
#     print(a[j],b[j])
    # j=j+1




# list1=[10,20,30,40]
# list2=[100,200,300,400]
# i=0
# a=[]
# b=[]
# while i<len(list1):
#     a.append(list1[i])
#     i=i+1
# i=1
# while i<len(list2)+1:
#     b.append(list2[-i])
#     i=i+1
# j=0
# while j<len(a) and j<len(b):
#     print(a[j],b[j])
#     j=j+1
# i = 0
# while i < len(list1):
#     a.append(list1[i])
#     b.append(list2[i])
#     i = i + 1
# print(a,b)
# j = 0
# while j < len(a):
#     print(a[j],b[-(j+1)])
#     j = j + 1




# list1=[10,20,30,40]
# list2=[100,200,300,400]
# i=0
# while i<len(list1):
#     print(list1[i],list2[-(i+1)])
#     i=i+1
