# i=0
# c=0
# d=0
# e=0
# f=0
# g=0
# while i<=20:
#     num=int(input("enter the number")) 
#     if num%2==0:
#         c=c+1
#     else:
#         d=d+1
#     if num<0:
#         e=e+1  
#     elif num>0:
#         f=f+1
#     else:
#         g=g+1
#     i=i+1
# print(c,"it is even number")
# print(d,"it is odd number")
# print(e,"it is positive number")
# print(f,"it is negative number")
# print(g,"it is 0s number")
