# n=["n","i","t","i","n"] 
# i=0
# j=len(n)-1
# while i<len(n):
#     if n[i]==n[j]:
#         print("it is palidrom")
#         i=i+1
#         break
#     else:
#         print("it is not palidrom")


# m=["n","a","i","n","a"]
# i=0
# k=len(m)-1
# while i<len(m):
#     if m[i]==m[k]:
#         print("it is palidrom")
#     else:
#         print("it is not palidrom")
#         i=i+1
#         break